name: 🔨 Build Test

on:
  pull_request:
    paths:
      - '**.go'
  workflow_dispatch:


jobs:  
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: projectdiscovery/actions/setup/go@v1

      - name: Build validate-domains
        run: go build .
        working-directory: cmd/validate-domains/

      - name: Build http-tester
        run: go build .
        working-directory: cmd/httpx-tester/

      - name: Build bbp scope
        run: go build .
        working-directory: cmd/httpx-tester/

      - name: Test
        run: go test ./...
        working-directory: .