name: httpx check cron

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-job:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true

      - name: Get all bbp policy URLs
        run: jq -r '.programs[].url' chaos-bugbounty-list.json > urls.txt

      - name: Installing Validate domains binary
        run: >
          go install
          github.com/projectdiscovery/public-bugbounty-programs/cmd/httpx-tester
        shell: bash

      - name: Checking URL availability
        run: |
          httpx-tester -file urls.txt
        shell: bash

      - name: checking programs with unaccessible policy URL
        run: |
          if [[ -s invalid.txt ]]; then
              echo "programs with not accessible URL policy found: $(cat invalid.txt)"
              exit 1
          fi