name: ✅ Policy Checks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: projectdiscovery/actions/setup/go@v1
      - run: make policy-checks
